using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.Architecture;
using Autodesk.Revit.UI;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Number
{
    [Transaction(TransactionMode.Manual)]
    public class Main : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var uiapp = commandData.Application;
            var uidoc = uiapp.ActiveUIDocument;
            Document doc = commandData.Application.ActiveUIDocument.Document;

            //NumberSelection numberSelection = new NumberSelection(uiapp, uidoc, doc);
            //numberSelection.Selection();

            var window = new MainPanel(uiapp, uidoc, doc);
            window.ShowDialog();

            return Result.Succeeded;
        }


    }
}